Set Up Redux ToolKit
atlp-rwanda/dynamites-ecomm-fe pull request #33
Opened 2024-06-20 13:28 UTC by 13XAVI

## User Story: Set Up Frontend Project

### Overview
As a Frontend Developer, I want to set up a new frontend project with a well-structured foundation, so that it can be easily developed and maintained by the team.

### Acceptance Criteria
- [ ] Redux Toolkit is configured to manage the application's state efficiently.

### Completed Task Checklist

- [ ] Configure Redux Toolkit

By following these tasks and verifying the acceptance criteria, the frontend project will have a solid foundation, making it easier to develop and maintain.

2024-06-20 15:27 UTC, wayneleon1 approved these changes
Good job

2024-06-20 15:34 UTC, jkarenzi approved these changes

2024-06-21 05:13 UTC, dushimeemma requested changes

2024-06-21 05:13 UTC, dushimeemma commented on .eslintrc.cjs
Why have you changed this file?

2024-06-21 05:13 UTC, dushimeemma commented on src/Redux/EcommerceReducer.ts
what is the use of this file in configuring redux?

2024-06-21 05:13 UTC, dushimeemma commented on src/index.css
why have you changed this file while setting up redux?

2024-06-21 05:13 UTC, dushimeemma commented on src/main.tsx
> +  <Provider store={store}>
Exchange lines 10 and 9.
ie: Line 10 should come first on line 9 and line 9 should be on line 10.
example:
`<React.StrictMode>
      <Provider store={store}>
            <App />
      </Provider>
</React.StrictMode>`

2024-06-21 09:10 UTC, closed without merging