creating passwrod reset functionality
atlp-rwanda/dynamites-ecomm-fe pull request #61
Opened 2024-07-02 01:30 UTC by niyobern

**Summary**
This pull request introduces significant updates to the authentication flow within our application, specifically focusing on the password recovery and reset functionalities. By refining these processes, we aim to provide a more secure and user-friendly experience for our users when they need to recover access to their accounts

**Changes**

- **Password Recovery Initiation:** Implemented an asynchronous thunk action, `requestPasswordReset`, which sends a request to the backend with the user's email. This initiates the password recovery process by generating a recovery token and sending it to the user's email address (this needs a fix).

- **Password Reset:** Added another asynchronous thunk action, `resetPassword`, which allows users to reset their password using the recovery token sent to their email. This action sends the token and the new password to the backend, where the token is verified, and the password is updated.

**Technical Details**

- Both thunk actions utilize [axios](https://github.com/axios/axios) for making HTTP POST requests to the backend.

- Error handling is implemented to return the error response data using `rejectWithValue` in case of request failures, ensuring that the application can gracefully inform the user about any issues encountered during the process.

**Testing**
...Pending

2024-07-03 10:48 UTC, ambroisegithub approved these changes
It looks good for merge!!!

2024-07-03 11:21 UTC, 13XAVI approved these changes

2024-07-03 11:43 UTC, bertrandshema approved these changes
It is good fir me

2024-07-03 14:20 UTC, wayneleon1 requested changes, later dismissed

2024-07-03 14:20 UTC, wayneleon1 commented on src/app/slices/authSlices.ts
you must follow the rules for creating slices for example : features/product/productslices.ts.
, you are just keep creating for slices into app directory which is not the best practice

2024-07-03 18:40 UTC, dushimeemma approved these changes

2024-07-03 18:51 UTC, niyobern commented on src/app/slices/authSlices.ts
Why do you create a separate directory for redux while app directory was in first place created for that?

2024-07-03 21:40 UTC, niyobern commented on src/app/slices/authSlices.ts
What I think can remove ambiguity and make the code structure more organized is keeping all redux code in one place, grouping related feautures together.

2024-07-04 04:46 UTC, dushimeemma requested changes

2024-07-04 04:46 UTC, dushimeemma commented on src/app/slices/authSlices.ts
@wayneleon1 I agree with you.
@niyobern please work on this.

2024-07-10 08:28 UTC, dushimeemma approved these changes

2024-07-10 08:29 UTC, merged