side bar implementation
atlp-rwanda/dynamites-ecomm-fe pull request #75
Opened 2024-07-05 16:08 UTC by Dawaic6

2024-07-08 09:57 UTC, wayneleon1 approved these changes

2024-07-08 10:30 UTC, EddyShimwa approved these changes
👍

2024-07-08 10:50 UTC, niyobern approved these changes

2024-07-08 11:42 UTC, dushimeemma requested changes

2024-07-08 11:42 UTC, dushimeemma commented on src/routes/AppRoutes.tsx
> +      <Route path="Dashboard" element={<DashboardLayout />}></Route>
I think the path can be `/dashboard` to have similarities with the above paths

2024-07-08 11:42 UTC, dushimeemma commented on src/components/DashboardSideNav.tsx
> +                <span className="text-black">{subItem.name}</span>
I think you can set color to white on active item.

2024-07-09 11:42 UTC, dushimeemma approved these changes

2024-07-09 11:42 UTC, merged